@startuml

actor 用户端 #red
participant 审批平台
participant 征信网关
participant 决策引擎
actor 审批员 #red

用户端 -> 审批平台: 提交订单
审批平台 -> 审批平台: 保存订单
审批平台 -> 征信网关: 调取征信数据
征信网关 --> 审批平台: 返回征信数据
审批平台 -> 审批员: 展示订单
审批员 -> 审批平台: 审核订单
审批平台 -> 决策引擎: 调用决策
决策引擎 --> 审批平台: 返回决策结果
审批平台 -> 审批员: 展示决策结果
审批员 -> 审批平台: 审核订单
审批平台 -> 用户端: 推送订单审核结果

@enduml