@startuml

actor 用户端 #red
participant 及贷审批平台
participant 灵机系统
participant 第三方征信平台
actor 审批员 #red

用户端 -> 及贷审批平台: 创建 订单
及贷审批平台 -> 及贷审批平台: 保存 订单
及贷审批平台 -> 灵机系统: 推送资料[订单资料]
及贷审批平台 -> 及贷审批平台: 创建 决策任务

loop n 次(具体根据任务数量)
及贷审批平台 -> 及贷审批平台: 获取 决策任务
及贷审批平台 -> 灵机系统: 调取决策[决策任务]
灵机系统 --> 第三方征信平台: 调取 征信数据
灵机系统 --> 灵机系统: 保存 征信数据
灵机系统 --> 灵机系统: 执行决策[决策任务]
灵机系统 -> 及贷审批平台: 推送 审核结果
end
alt 决策结果 "A"
及贷审批平台 -> 用户端: 推送审核通过通知[订单]
else 决策结果 "D"
及贷审批平台 -> 用户端: 推送审核拒绝通知[订单]
else 决策结果 "RD"
及贷审批平台 -> 审批员: 展示 订单
审批员 -> 及贷审批平台: 审核 订单
及贷审批平台 -> 用户端: 推送审核结果通知(通过/拒绝)[订单]
end

@enduml